---
title: "Lego Brick Colors"
author: "Jesse Fagan"
date: "24/01/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggthemes)
```

## Notes

Use the `brickr` package for something? https://github.com/ryantimpe/brickr

# Lego Colors by Year

Load the data

```{r}
agg_year_color_parts_count <- 
  read_csv('./agg_year_color_parts_count.csv') %>% 
  select(-X1)
```

```{r}
agg_year_color_parts_count %>% 
  group_by(rgb) %>% 
  summarize(total_count = sum(count)) %>% 
  arrange(desc(total_count))
```

Plot a single color over time.

```{r}
# part_rgb <- "05131D"
part_rgb <- "A0A5A9"
agg_year_color_parts_count %>% 
  filter(rgb == part_rgb) %>%
  filter(year != 2021) %>% 
  ggplot(aes(x = year, y = count)) +
  geom_line(color = paste0("#",part_rgb), size = 3)
```

Plot all the color

```{r}
agg_year_color_parts_count %>% 
  group_by(rgb) %>% 
  summarize(total_count = sum(count)) %>% 
  arrange(desc(total_count)) %>% 
  top_n(10) %>% 
  pull(rgb) ->
  top_colors
```

```{r}
agg_year_color_parts_count %>% 
  filter(rgb %in% top_colors) %>%
  filter(year != 2021) %>% 
  mutate(rgb = factor(rgb, levels = top_colors)) %>% 
  ggplot(aes(x = year, y = count, group = rgb, color = rgb)) +
  geom_line(size = 1) +
  geom_point() +
  scale_color_manual(values = paste0("#", top_colors))
```

## Alluvial diagram

Try running an example.

```{r}
library(ggalluvial)
data(Refugees, package = "alluvial")
country_regions <- c(
  Afghanistan = "Middle East",
  Burundi = "Central Africa",
  `Congo DRC` = "Central Africa",
  Iraq = "Middle East",
  Myanmar = "Southeast Asia",
  Palestine = "Middle East",
  Somalia = "Horn of Africa",
  Sudan = "Central Africa",
  Syria = "Middle East",
  Vietnam = "Southeast Asia"
)
Refugees$region <- country_regions[Refugees$country]
ggplot(data = Refugees,
       aes(x = year, y = refugees, alluvium = country)) +
  geom_alluvium(aes(fill = country, colour = country),
                alpha = .75, decreasing = FALSE) +
  scale_x_continuous(breaks = seq(2003, 2013, 2)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = -30, hjust = 0)) +
  scale_fill_brewer(type = "qual", palette = "Set3") +
  scale_color_brewer(type = "qual", palette = "Set3") +
  # facet_wrap(~ region, scales = "fixed") +
  ggtitle("refugee volume by country and region of origin")
```

```{r}
d <- Refugees %>% 
  group_by(year) %>% 
  mutate(med_refugees = mean(refugees)) %>% 
  ungroup() %>% 
  mutate(refugees = ifelse(refugees < med_refugees, -refugees, refugees))
ggplot(d, aes(x= year, y = refugees, 
                     alluvium = country, fill = country)) + 
  stat_alluvium(decreasing = FALSE)
```


```{r}
glimpse(Refugees)
```


```{r}
agg_year_color_parts_count %>% 
  filter(rgb %in% top_colors) %>%
  filter(year != 2021, year >= 1960) %>% 
  mutate(rgb = factor(rgb, levels = top_colors)) %>% 
  group_by(year) %>% 
  mutate(m_count = mean(count)) %>% 
  ungroup() %>% 
  mutate(count = ifelse(count < m_count, -count, count)) -> d
ggplot(d, aes(x = year, y = count, alluvium = rgb, fill = rgb)) +
  geom_alluvium(decreasing = FALSE, alpha = 0.8) +
  scale_fill_manual(values = paste0("#", top_colors)) +
  theme(legend.position = "none")
```

All the colors!

```{r}
agg_year_color_parts_count %>% 
  group_by(rgb) %>% 
  summarize(total_count = sum(count)) %>% 
  arrange(desc(total_count)) %>% 
  pull(rgb) -> color_order
agg_year_color_parts_count %>% 
  filter(year != 2021, year >= 1960) %>% 
  mutate(rgb = factor(rgb, levels = color_order)) %>% 
  group_by(year) %>% 
  arrange(year,desc(count)) %>% 
  # mutate(m_count = mean(count)) %>%
  # mutate(m_count = sum(count) / 2) %>% 
  # mutate(m_count = mean(count) * 4) %>%
  mutate(m_count = cumsum(count) / sum(count)) %>% 
  mutate(count = scales::rescale(count,c(5, 50))) %>% 
  ungroup() %>% 
  # mutate(count = ifelse(count < m_count, -count, count)) -> d
  mutate(count = ifelse(m_count > 0.65, -count, count)) -> d
ggplot(d, aes(x = year, y = count, alluvium = rgb, fill = rgb, color = rgb)) +
  geom_alluvium(decreasing = FALSE, alpha = 0.8) +
  scale_fill_manual(values = paste0("#", color_order)) +
  scale_color_manual(values = paste0("#", color_order)) +
  theme(legend.position = "none")
```

Normalize by sets.


```{r}
num_sets_by_year <- read_csv('num_sets_for_year.csv') %>% 
  select(-X1, num_sets = x)
agg_year_color_parts_count %>% 
  group_by(rgb) %>% 
  summarize(total_count = sum(count)) %>% 
  arrange(desc(total_count)) %>% 
  pull(rgb) -> color_order
d <- agg_year_color_parts_count %>% 
  filter(year != 2021, year >= 1960) %>% 
  mutate(rgb = factor(rgb, levels = color_order)) %>% 
  left_join(num_sets_by_year, by = 'year') %>% 
  group_by(year) %>% 
  arrange(year,desc(count)) %>% 
  mutate(m_count = cumsum(count) / sum(count)) %>% 
  mutate(count = count / num_sets) %>% 
  ungroup() %>% 
  mutate(count = ifelse(m_count > 0.65, -count, count))
ggplot(d) +
  geom_alluvium(decreasing = FALSE, alpha = 0.8, 
                aes(x = year, y = count, alluvium = rgb, fill = rgb, color = rgb)) +
  geom_text(data = tibble(yr = seq(1960,2020, by = 10)), y = 0, 
            aes(x = yr, label = yr),
            family = "Oswald", hjust = "left") + 
  scale_fill_manual(values = paste0("#", color_order)) +
  scale_color_manual(values = paste0("#", color_order)) +
  theme_void() +
  theme(legend.position = "none", plot.background = element_rect(fill = "pink"))
```

```{r}
ggsave(filename = "lego_streamgraph.svg",
       width = 32, height = 9)
```


Details for the notes.

```{r}
agg_year_color_parts_count %>% 
  filter(year == 2020) %>% 
  pull(count) %>% 
  sum
agg_year_color_parts_count %>% 
  filter(year == 2020) %>% 
  arrange(desc(count)) %>% 
  mutate(p = count / sum(count))
```

What's going on with 1963

```{r}

sets <- read_csv("sets.csv")
inventories <- read_csv("inventories.csv")
inventory_parts <- read_csv("inventory_parts.csv")
parts <- read_csv("parts.csv")
colors <- read_csv("colors.csv")

sets2 <- left_join(inventories, inventory_parts, by = c("id" = "inventory_id")) %>% 
  left_join(sets, by = c("set_num"))

sets2 %>% 
  filter(year == 1963) %>% 
  distinct(set_num, color_id) %>% 
  count(set_num) %>% 
  top_n(3)
  
sets %>% 
  filter(set_num == "LEGO-Modulex-1")
```

Here is the reason:
https://www.newelementary.com/2017/11/old-bricks-what-are-modulex-lego.html
https://rebrickable.com/blog/211/modulex-a-bit-of-history/


```{r}
num_sets_by_year <- read_csv('num_sets_for_year.csv') %>% 
  select(-X1, num_sets = x)
ggplot(num_sets_by_year, aes(x = year, y = num_sets)) +
  geom_line()
```


```{r}
sets2 %>% 
  filter(year == 2001) %>% 
  distinct(set_num, num_parts) %>% 
  arrange(desc(num_parts))
  
sets %>% 
  filter(set_num == "045-1")
```








